// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DgjQEVQvICF39vH4w5XI6gXo0fH3pA8',
    appId: '1:110274988062:web:c7c04736f49a33c7ce060f',
    messagingSenderId: '110274988062',
    projectId: 'bytetobitedb',
    authDomain: 'bytetobitedb.firebaseapp.com',
    storageBucket: 'bytetobitedb.firebasestorage.app',
    measurementId: 'G-WEPBK7CSMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB49Wmh8WMKK286r0_8X016tKgkfyMyxgs',
    appId: '1:110274988062:android:0f27bafec1de5624ce060f',
    messagingSenderId: '110274988062',
    projectId: 'bytetobitedb',
    storageBucket: 'bytetobitedb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfDxigdB0p_8dCU8CiASnylAGB5lUP_44',
    appId: '1:110274988062:ios:1b6d7d3f7a6b454bce060f',
    messagingSenderId: '110274988062',
    projectId: 'bytetobitedb',
    storageBucket: 'bytetobitedb.firebasestorage.app',
    iosBundleId: 'com.example.byteToBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfDxigdB0p_8dCU8CiASnylAGB5lUP_44',
    appId: '1:110274988062:ios:1b6d7d3f7a6b454bce060f',
    messagingSenderId: '110274988062',
    projectId: 'bytetobitedb',
    storageBucket: 'bytetobitedb.firebasestorage.app',
    iosBundleId: 'com.example.byteToBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DgjQEVQvICF39vH4w5XI6gXo0fH3pA8',
    appId: '1:110274988062:web:ccb91f0616d0dc72ce060f',
    messagingSenderId: '110274988062',
    projectId: 'bytetobitedb',
    authDomain: 'bytetobitedb.firebaseapp.com',
    storageBucket: 'bytetobitedb.firebasestorage.app',
    measurementId: 'G-G5PGJ8Y26Y',
  );
}
